# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: MSVC
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: >
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\vsdevcmd" -arch=x64 &&
          cmake -P ci.cmake
        env:
          CC: cl
          CXX: cl
          PMM_DOCKER_TESTS: 'NO'
        displayName: Run all tests

  - job: MinGW
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: >
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\vsdevcmd" -arch=x64 &&
          cmake -P ci.cmake
        env:
          CC: gcc
          CXX: g++
          PMM_DOCKER_TESTS: 'NO'
        displayName: Run all tests

  - job: LinuxDocker
    pool:
      vmImage: ubuntu-16.04

    steps:
      - script: cmake -P ci.cmake
        env:
          PMM_DOCKER_TESTS: 'TRUE'
        displayName: Run Docker tests
